// Generated by Wrangler by running `wrangler types`

interface Env {
	ars: KVNamespace;
	BETTER_AUTH_SECRET: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	DB: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	BUCKET_NAME: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	CLOUDFLARE_R2_ENDPOINT: string;
	ARS_R2: R2Bucket;
	ARS_DB: D1Database;
	ASSETS: Fetcher;
}
