// Generated by Wrangler by running `wrangler types`

interface Env {
	ars: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	DB: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	PROJECT_STATE: string;
	SITE: string;
	BUCKET_NAME: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	CLOUDFLARE_R2_ENDPOINT: string;
	ARS_R2: R2Bucket;
	ARS_DB: D1Database;
	ASSETS: Fetcher;
}
