#:schema node_modules/wrangler/config-schema.json
name = "timeless"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat_v2"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
BETTER_AUTH_SECRET= ""
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""

[[d1_databases]]
binding = "DB"
database_name = "ars"
database_id = "e7edd58c-059b-4c32-bd3e-14732a992eff"

[[kv_namespaces]]
binding = "ars"
id = "460c76c5c82d4f8cbcd52e46342ab37c"

[[r2_buckets]]
bucket_name = "ars"
binding = "ars"

